
import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Mina Magdy
 */
public class BandAid extends javax.swing.JFrame {

    /**
     * Creates new form BandAid
     */
    public BandAid() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDiabeticBleeding = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jbtnEpilepticFit = new javax.swing.JButton();
        jbtnSevereBleeding = new javax.swing.JButton();
        jbtnShortnessOfBreath = new javax.swing.JButton();
        jbtnFainting = new javax.swing.JButton();
        jbtnBurns = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtYouShouldNotDo = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtxtYouShouldDo = new javax.swing.JTextArea();
        jPanel13 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jbtnPcDoctor = new javax.swing.JButton();
        jbtnMedicines = new javax.swing.JButton();
        jbtnBandAid = new javax.swing.JButton();
        jbtnFood = new javax.swing.JButton();

        jDiabeticBleeding.setBackground(new java.awt.Color(204, 255, 255));
        jDiabeticBleeding.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jDiabeticBleeding.setForeground(new java.awt.Color(0, 0, 0));
        jDiabeticBleeding.setText("Diabetic Bleeding");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 255, 255));
        jButton1.setText("Epileptic Fit");

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 255, 255));
        jButton2.setText("Fainting");

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 255, 255));
        jButton3.setText("Burns");

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(204, 255, 255));
        jButton4.setText("Shortness Of Breath");

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText(" Choose The Emergency");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText(" You Should Do: ");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText(" You Shouldn't Do: ");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(51, 0, 51));
        jPanel5.setForeground(new java.awt.Color(51, 0, 51));
        jPanel5.setLayout(new java.awt.CardLayout());

        jPanel6.setBackground(new java.awt.Color(57, 62, 70));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jbtnEpilepticFit.setBackground(new java.awt.Color(153, 153, 153));
        jbtnEpilepticFit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnEpilepticFit.setForeground(new java.awt.Color(0, 0, 0));
        jbtnEpilepticFit.setText("Epileptic Fit");
        jbtnEpilepticFit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEpilepticFitActionPerformed(evt);
            }
        });

        jbtnSevereBleeding.setBackground(new java.awt.Color(153, 153, 153));
        jbtnSevereBleeding.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnSevereBleeding.setForeground(new java.awt.Color(0, 0, 0));
        jbtnSevereBleeding.setText("Severe Bleeding");
        jbtnSevereBleeding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSevereBleedingActionPerformed(evt);
            }
        });

        jbtnShortnessOfBreath.setBackground(new java.awt.Color(153, 153, 153));
        jbtnShortnessOfBreath.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnShortnessOfBreath.setForeground(new java.awt.Color(0, 0, 0));
        jbtnShortnessOfBreath.setText("Shortness Of Breath");
        jbtnShortnessOfBreath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnShortnessOfBreathActionPerformed(evt);
            }
        });

        jbtnFainting.setBackground(new java.awt.Color(153, 153, 153));
        jbtnFainting.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnFainting.setForeground(new java.awt.Color(0, 0, 0));
        jbtnFainting.setText("Fainting");
        jbtnFainting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFaintingActionPerformed(evt);
            }
        });

        jbtnBurns.setBackground(new java.awt.Color(153, 153, 153));
        jbtnBurns.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnBurns.setForeground(new java.awt.Color(0, 0, 0));
        jbtnBurns.setText("Burns");
        jbtnBurns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBurnsActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 7));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText(" Choose The Emergency ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(153, 153, 153));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 7));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("You Should Do:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jtxtYouShouldNotDo.setEditable(false);
        jtxtYouShouldNotDo.setColumns(20);
        jtxtYouShouldNotDo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtYouShouldNotDo.setRows(5);
        jScrollPane1.setViewportView(jtxtYouShouldNotDo);

        jtxtYouShouldDo.setEditable(false);
        jtxtYouShouldDo.setColumns(20);
        jtxtYouShouldDo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtYouShouldDo.setRows(5);
        jScrollPane3.setViewportView(jtxtYouShouldDo);

        jPanel13.setBackground(new java.awt.Color(153, 153, 153));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 7));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("You Shouldn't Do:");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE)
                        .addComponent(jScrollPane1))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnEpilepticFit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnShortnessOfBreath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnSevereBleeding, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnFainting, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnBurns, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jbtnSevereBleeding, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jbtnShortnessOfBreath, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnEpilepticFit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jbtnFainting, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jbtnBurns, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149))))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Band Aid");

        jbtnPcDoctor.setBackground(new java.awt.Color(255, 255, 255));
        jbtnPcDoctor.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnPcDoctor.setForeground(new java.awt.Color(0, 0, 0));
        jbtnPcDoctor.setIcon(new javax.swing.ImageIcon("D:\\Coding\\Java\\PC-Doctor\\images\\Logo.jpg")); // NOI18N
        jbtnPcDoctor.setText("  PC Doctor");
        jbtnPcDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPcDoctorActionPerformed(evt);
            }
        });

        jbtnMedicines.setBackground(new java.awt.Color(255, 255, 255));
        jbtnMedicines.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnMedicines.setForeground(new java.awt.Color(0, 0, 0));
        jbtnMedicines.setIcon(new javax.swing.ImageIcon("D:\\Coding\\Java\\PC-Doctor\\images\\Medicines.png")); // NOI18N
        jbtnMedicines.setText("  Medicines");
        jbtnMedicines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMedicinesActionPerformed(evt);
            }
        });

        jbtnBandAid.setBackground(new java.awt.Color(255, 255, 255));
        jbtnBandAid.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnBandAid.setForeground(new java.awt.Color(0, 0, 0));
        jbtnBandAid.setIcon(new javax.swing.ImageIcon("D:\\Coding\\Java\\PC-Doctor\\images\\BandAid.png")); // NOI18N
        jbtnBandAid.setText("  Band Aid");
        jbtnBandAid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBandAidActionPerformed(evt);
            }
        });

        jbtnFood.setBackground(new java.awt.Color(255, 255, 255));
        jbtnFood.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnFood.setForeground(new java.awt.Color(0, 0, 0));
        jbtnFood.setIcon(new javax.swing.ImageIcon("D:\\Coding\\Java\\PC-Doctor\\images\\Food.png")); // NOI18N
        jbtnFood.setText("  Food");
        jbtnFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFoodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jbtnPcDoctor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(663, 663, 663))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtnMedicines, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnBandAid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnFood, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jbtnPcDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnMedicines, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jbtnBandAid, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jbtnFood, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(255, 255, 255))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1306, 1306, 1306)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnShortnessOfBreathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnShortnessOfBreathActionPerformed
        //you should 
        jtxtYouShouldDo.setText("1- Stand behind the injured person.\n2- Place one foot slightly in front of the other for balance.");
        jtxtYouShouldDo.setText(jtxtYouShouldDo.getText() + "3- Wrap the arms around the injured person's waist.\n4- Lean the injured person forward slightly.\n");
        jtxtYouShouldDo.setText(jtxtYouShouldDo.getText() + "5- Make a fist with the other hand, then place it above the navel area.\n6- Hold the fist with the other hand, then direct a strong pressure on the abdomen quickly upwards.\n");
        jtxtYouShouldDo.setText(jtxtYouShouldDo.getText() + "7- Perform 6 to 10 abdominal pressures until the stuck object is removed.");
        //you shouldn't
        jtxtYouShouldNotDo.setText("1- any thing If the person is able to breathe hard, they should continue to cough.");
        
    }//GEN-LAST:event_jbtnShortnessOfBreathActionPerformed

    private void jbtnEpilepticFitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEpilepticFitActionPerformed
        // TODO add your handling code here:
        jtxtYouShouldDo.setText("1- Note the depletion in the shift.\n");
        jtxtYouShouldDo.setText(jtxtYouShouldDo.getText() + "2- Protect people with seizures by removing any harmful objects near them and keeping them away from danger sources such as the stairs.\n");
        jtxtYouShouldDo.setText(jtxtYouShouldDo.getText() + "3- Dimensions of the glasses the patient used.\n");
        jtxtYouShouldDo.setText(jtxtYouShouldDo.getText() + "4- Support the person's head to prevent him from hitting the ground by placing a piece of cloth or a jacket.\n");
        jtxtYouShouldDo.setText(jtxtYouShouldDo.getText() + "5- If the seizure lasts more than 5 minutes or more, an ambulance should be called.\n");
        
        jtxtYouShouldNotDo.setText("1- Immobilization of the patient when he had a seizure.\n");
        jtxtYouShouldNotDo.setText(jtxtYouShouldNotDo.getText() + "2- Do not gather around the injured person.\n");
        jtxtYouShouldNotDo.setText(jtxtYouShouldNotDo.getText() + "3- Placing any object in the mouth of the injured person or between his teeth.\n");
        jtxtYouShouldNotDo.setText(jtxtYouShouldNotDo.getText() + "4- Attempting to move the injured person during the seizure.\n");
        jtxtYouShouldNotDo.setText(jtxtYouShouldNotDo.getText() + "5- Do not panic and assume that the casualty knows what is happening or what has happened.\n");
        jtxtYouShouldNotDo.setText(jtxtYouShouldNotDo.getText() + "6- Giving the injured person any kind of food or drink until he fully recovers.\n");
    }//GEN-LAST:event_jbtnEpilepticFitActionPerformed

    private void jbtnFaintingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFaintingActionPerformed

        
        //you should
        jtxtYouShouldDo.setText("1- Help the person lie on their back if the person is sitting in a chair.\n2- Roll the person to their side if they are unconscious, and check that they are breathing and have a regular heartbeat.\n");
        jtxtYouShouldDo.setText(jtxtYouShouldDo.getText() + "3- Elevate the person's feet about 30 cm above the level of the heart if possible to restore blood flow to the brain.\n4- Loosen collars, belts and other tight clothing if the fainting spell is caused by heat, and try to cool the person down by wiping them with a damp cloth or ventilating them\n");
        jtxtYouShouldDo.setText(jtxtYouShouldDo.getText() + "5- make sure there is plenty of fresh air and ask others to move away and open a window if the person is in a room. To make sure there is plenty of fresh air and ask others to move away and open the window if the person is in a room.\n6- Call the emergency number if the person does not regain consciousness within one minute.");
        //you shouldn't
        jtxtYouShouldNotDo.setText("1- make the fainting person get up after a short time, so that he does not faint again.\n");

        
        
    }//GEN-LAST:event_jbtnFaintingActionPerformed

    private void jbtnPcDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPcDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnPcDoctorActionPerformed

    private void jbtnMedicinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMedicinesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnMedicinesActionPerformed

    private void jbtnBandAidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBandAidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnBandAidActionPerformed

    private void jbtnFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFoodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnFoodActionPerformed

    private void jbtnSevereBleedingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSevereBleedingActionPerformed
        //you should
        jtxtYouShouldDo.setText("1- Remove clothing or dirt from the wound area.\n2- Place a sterile bandage or piece of clean cloth over the wound.\n");
        jtxtYouShouldDo.setText(jtxtYouShouldDo.getText() + "3- Press the bandage firmly with the palm of your hand to control bleeding.\n4- Secure the dressing with tape or maintain pressure with your hands.\n");
        jtxtYouShouldDo.setText(jtxtYouShouldDo.getText() + "5- Immobilize the affected body part as much as possible.");
       //you shouldn't
        jtxtYouShouldNotDo.setText("1- remove large or deeply embedded objects.\n2- examine the wound and do not attempt to clean it either.\n");
        jtxtYouShouldNotDo.setText(jtxtYouShouldNotDo.getText() + "3- press directly on the eye wound or on the object that is embedded in it.\n");
        jtxtYouShouldNotDo.setText(jtxtYouShouldNotDo.getText() + "4- remove the gauze or bandage ,If blood leaks through the gauze or cloth on the wound,\n place another medical dressing over it, and keep pressing firmly on the wound.");
    }//GEN-LAST:event_jbtnSevereBleedingActionPerformed

    private void jbtnBurnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBurnsActionPerformed
        // TODO add your handling code here:
        jtxtYouShouldDo.setText("1- Protect the injured person from harm.\n");
        jtxtYouShouldDo.setText(jtxtYouShouldDo.getText() + "2- Remove jewelry, belts, etc., especially around burned areas such as the neck.\n");
        jtxtYouShouldDo.setText(jtxtYouShouldDo.getText() + "3- Take a pain reliever if necessary to relieve pain.\n");
        jtxtYouShouldDo.setText(jtxtYouShouldDo.getText() + "4- Cover the burn area with a damp bandage or a clean, cool cloth.\n");
        jtxtYouShouldDo.setText(jtxtYouShouldDo.getText() + "5- Cover open blisters with a dry, sterile bandage.\n");
        
        jtxtYouShouldNotDo.setText("1- Remove burnt clothing stuck to the skin.\n");
        jtxtYouShouldNotDo.setText(jtxtYouShouldNotDo.getText() + "2- Cover the burn with an adhesive bandage.\n");
        jtxtYouShouldNotDo.setText(jtxtYouShouldNotDo.getText() + "3- Place large burn areas in cold water to avoid trauma to the injured person.\n");
        jtxtYouShouldNotDo.setText(jtxtYouShouldNotDo.getText() + "4- Use ice directly on the burnt area.\n");
        jtxtYouShouldNotDo.setText(jtxtYouShouldNotDo.getText() + "5- Applying any ointments, butter, toothpaste, or other remedies to the burn.\n");
        jtxtYouShouldNotDo.setText(jtxtYouShouldNotDo.getText() + "6- Touching or opening the blisters resulting from the burn.\n");
        jtxtYouShouldNotDo.setText(jtxtYouShouldNotDo.getText() + "7- Putting thin cotton on the affected area, which may irritate the skin.\n");
        
    }//GEN-LAST:event_jbtnBurnsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BandAid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BandAid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BandAid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BandAid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BandAid frame = new BandAid();
//                frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
//                frame.setResizable(false);
//                frame.pack();
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jDiabeticBleeding;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton jbtnBandAid;
    private javax.swing.JButton jbtnBurns;
    private javax.swing.JButton jbtnEpilepticFit;
    private javax.swing.JButton jbtnFainting;
    private javax.swing.JButton jbtnFood;
    private javax.swing.JButton jbtnMedicines;
    private javax.swing.JButton jbtnPcDoctor;
    private javax.swing.JButton jbtnSevereBleeding;
    private javax.swing.JButton jbtnShortnessOfBreath;
    private javax.swing.JTextArea jtxtYouShouldDo;
    private javax.swing.JTextArea jtxtYouShouldNotDo;
    // End of variables declaration//GEN-END:variables
}
