import java.util.*;
import java.util.List;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.xml.crypto.Data;

/**
 *
 * @author connect
 */
public class Foods extends javax.swing.JFrame {

    /**
     * Creates new form Foods
     */
    public Foods() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jfood = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextSearch = new javax.swing.JTextField();
        jOkSearch = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMedicines = new javax.swing.JButton();
        jBandAid = new javax.swing.JButton();
        jFoods = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jcalories = new javax.swing.JLabel();
        jname = new javax.swing.JLabel();
        jadvantage = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jfat = new javax.swing.JLabel();
        jcarb = new javax.swing.JLabel();
        jprotein = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1350, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 103, 44));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jfood.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jfood.setForeground(new java.awt.Color(255, 255, 255));
        jfood.setText("Foods");
        jPanel1.add(jfood, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextSearch.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTextSearch.setBorder(null);
        jTextSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSearchActionPerformed(evt);
            }
        });
        jPanel2.add(jTextSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 170, 40));

        jOkSearch.setBackground(new java.awt.Color(16, 18, 23));
        jOkSearch.setIcon(new javax.swing.ImageIcon("/home/anwar/NetBeansProjects/PcDoctor/src/main/java/com/images/search2.jpg")); // NOI18N
        jOkSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOkSearchActionPerformed(evt);
            }
        });
        jPanel2.add(jOkSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 230, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 1130, 60));

        jPanel3.setBackground(new java.awt.Color(153, 103, 44));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("PC Docter");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 113, -1, -1));
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 57, 102, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("/home/anwar/NetBeansProjects/PcDoctor/src/main/java/com/images/Logo.jpg")); // NOI18N
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 90, 80));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 210, 140));

        jMedicines.setBackground(new java.awt.Color(255, 255, 255));
        jMedicines.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMedicines.setForeground(new java.awt.Color(0, 0, 0));
        jMedicines.setText("  Medicines");
        jMedicines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMedicinesActionPerformed(evt);
            }
        });
        jPanel3.add(jMedicines, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 221, 52));

        jBandAid.setBackground(new java.awt.Color(246, 249, 254));
        jBandAid.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jBandAid.setForeground(new java.awt.Color(0, 0, 0));
        jBandAid.setText("   Band Aid ");
        jBandAid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBandAidActionPerformed(evt);
            }
        });
        jPanel3.add(jBandAid, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 221, 49));

        jFoods.setBackground(new java.awt.Color(255, 255, 255));
        jFoods.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jFoods.setForeground(new java.awt.Color(0, 0, 0));
        jFoods.setText("    Foods      ");
        jFoods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFoodsActionPerformed(evt);
            }
        });
        jPanel3.add(jFoods, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 221, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 800));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setName(""); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jcalories.setBackground(new java.awt.Color(204, 204, 204));
        jcalories.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jcalories.setForeground(new java.awt.Color(0, 0, 0));
        jcalories.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jcalories.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Calories", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 24), new java.awt.Color(153, 103, 44)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(153, 103, 44))); // NOI18N
        jcalories.setOpaque(true);
        jPanel6.add(jcalories, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 280, 130));

        jname.setBackground(new java.awt.Color(204, 204, 204));
        jname.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jname.setForeground(new java.awt.Color(0, 0, 0));
        jname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jname.setText("Name ");
        jname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 103, 44), 2, true));
        jname.setOpaque(true);
        jPanel6.add(jname, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 400, 70));

        jadvantage.setBackground(new java.awt.Color(204, 204, 204));
        jadvantage.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jadvantage.setForeground(new java.awt.Color(0, 0, 0));
        jadvantage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        jadvantage.setOpaque(true);
        jPanel6.add(jadvantage, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 1000, 120));

        jLabel7.setFont(new java.awt.Font("Ubuntu Mono", 1, 36)); // NOI18N
        jLabel7.setForeground(java.awt.Color.black);
        jLabel7.setText("Advantage:");
        jLabel7.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, -1, -1));

        jfat.setBackground(new java.awt.Color(204, 204, 204));
        jfat.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jfat.setForeground(new java.awt.Color(0, 0, 0));
        jfat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jfat.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fat", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 24), new java.awt.Color(153, 103, 44)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP)); // NOI18N
        jfat.setOpaque(true);
        jPanel6.add(jfat, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, 280, 130));

        jcarb.setBackground(new java.awt.Color(204, 204, 204));
        jcarb.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jcarb.setForeground(new java.awt.Color(0, 0, 0));
        jcarb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jcarb.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Carb", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 24), new java.awt.Color(153, 103, 44)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(153, 103, 44))); // NOI18N
        jcarb.setOpaque(true);
        jPanel6.add(jcarb, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 280, 130));

        jprotein.setBackground(new java.awt.Color(204, 204, 204));
        jprotein.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jprotein.setForeground(new java.awt.Color(0, 0, 0));
        jprotein.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jprotein.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Protein", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 1, 24), new java.awt.Color(153, 103, 44)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP)); // NOI18N
        jprotein.setOpaque(true);
        jPanel6.add(jprotein, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 280, 130));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 60, 1130, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMedicinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMedicinesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMedicinesActionPerformed

    private void jFoodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFoodsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFoodsActionPerformed

    private void jBandAidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBandAidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBandAidActionPerformed

    private void jTextSearchActionPerformed(java.awt.event.ActionEvent evt) {                                            
        jOkSearch.doClick();
    }
    
    private void jOkSearchActionPerformed(java.awt.event.ActionEvent evt) {                                          
        DataFoods food = searchFood(jTextSearch.getText().toLowerCase().trim());
        DataFoods similar = searchFoodSimilar(jTextSearch.getText().toLowerCase().trim());
        if(food != null || (similar != null && foundSimilar(similar) == true)){
            if(food == null) food = similar;
            food.name = food.name.substring(0, 1).toUpperCase() + food.name.substring(1);
            jname.setText(food.name);
            jcalories.setText(food.Calories);
            jprotein.setText(food.protein);
            jcarb.setText(food.carb);
            jfat.setText(food.fat);
            jadvantage.setText(food.advantage);
        }
        else {
            notFound();
        }
    }


    /**
     * @param args the command line arguments
     */
//************************************************************************************************************************

    public static void notFound(){
        JFrame frame = new JFrame();
        String message = "Food not found!";
        JOptionPane.showMessageDialog(frame, message);
    }

    public static boolean foundSimilar(DataFoods food){
        JFrame frame = new JFrame();
        String message = "Did you mean " + food.name + "?";
        int reply = JOptionPane.showConfirmDialog(frame, message, "Food not found!", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            return true;
        }
        return false;
    }

    public static DataFoods searchFood(String name) {
        for(DataFoods data : dataFoods){
            if (data.name.equals(name)){
                return new DataFoods(data);
            }
        }
        return null;
    }
    public static DataFoods searchFoodSimilar(String name) {
        double max_same_chars = 0.0;
        DataFoods d = null;
        for (DataFoods data : dataFoods) {
            if(calc_percentage(data.name, name) > max_same_chars){
                d = new DataFoods(data);
                max_same_chars = calc_percentage(d.name, name);
            }
        }
        return d;
    }
    
    public static double calc_percentage(String a, String b){
        double cb = 0;
        for(int i = 0; i < b.length(); i++){
            for(int j = 0; j < a.length(); j++){
                if(b.charAt(i) == a.charAt(j)){
                    cb++;
                    break;
                }
            }
        }
        return ((cb / a.length()) * 100) >= 50.0 ? ((cb / a.length()) * 100) : 0.0;
    }

    public static class DataFoods {
        public String name;
        public String Calories;
        public String protein;
        public String carb;
        public String fat;
        public String advantage;
        DataFoods(String name, String Calories, String protein, String carb, String fat, String advantage){
            this.name = name;
            this.Calories = Calories;
            this.protein = protein;
            this.carb = carb;
            this.fat = fat;
            this.advantage = advantage;
        }
        DataFoods(DataFoods data){
            this.name = data.name;
            this.Calories = data.Calories;
            this.protein = data.protein;
            this.carb = data.carb;
            this.fat = data.fat;
            this.advantage = data.advantage;
        }
    }

    public static List <DataFoods> dataFoods = new ArrayList<DataFoods>();
    // fill data
    public static void fillDataFoods() {
        dataFoods.add(new DataFoods("apple", "52", "0.3", "13.8", "0.2", "Apples are rich in antioxidants, which may help protect against heart disease and cancer. They're also a good source of fiber, which can help keep you regular and lower your risk of heart disease and diabetes."));
        dataFoods.add(new DataFoods("banana", "89", "1.1", "23.0", "0.3", "Bananas are a good source of potassium, which can help lower blood pressure. They're also a good source of fiber, which can help keep you regular and lower your risk of heart disease and diabetes."));
        dataFoods.add(new DataFoods("orange", "47", "0.9", "11.8", "0.1", "Oranges are a good source of vitamin C, which can help boost your immune system. They're also a good source of fiber, which can help keep you regular and lower your risk of heart disease and diabetes."));
        dataFoods.add(new DataFoods("grape", "69", "0.7", "18.1", "0.3", "Grapes are a good source of fiber, which can help keep you regular and lower your risk of heart disease and diabetes."));
        dataFoods.add(new DataFoods("watermelon", "30", "0.6", "7.7", "0.2", "Watermelon is a good source of vitamin A, which can help boost your immune system."));
        dataFoods.add(new DataFoods("melon", "30", "0.6", "7.7", "0.2", "Watermelon is a good source of vitamin A, which can help boost your immune system."));
        dataFoods.add(new DataFoods("rice", "130", "2.7", "28.0", "0.4", "Rice is a good source of fiber, which can help keep you regular and lower your risk of heart disease and diabetes."));
        dataFoods.add(new DataFoods("bread", "64", "2.4", "11.3", "0.6", "Bread is a good source of fiber, which can help keep you regular and lower your risk of heart disease and diabetes."));
        dataFoods.add(new DataFoods("pasta", "131", "5.5", "23.0", "1.5", "Pasta is a good source of fiber, which can help keep you regular and lower your risk of heart disease and diabetes."));
        dataFoods.add(new DataFoods("potato", "77", "2.0", "17.4", "0.1", "Potatoes are a good source of fiber, which can help keep you regular and lower your risk of heart disease and diabetes."));
        dataFoods.add(new DataFoods("tomato", "18", "0.9", "3.9", "0.2", "Tomatoes are a good source of vitamin C, which can help boost your immune system."));
        dataFoods.add(new DataFoods("egg", "155", "12.7", "1.1", "11.0", "Eggs are a good source of protein, which can help you feel full and boost your metabolism."));
        dataFoods.add(new DataFoods("milk", "42", "3.3", "4.6", "1.9", "Milk is a good source of calcium, which can help build strong bones and teeth."));
        dataFoods.add(new DataFoods("chicken", "239", "31.6", "0.0", "10.6", "Chicken is a good source of protein, which can help you feel full and boost your metabolism."));
        dataFoods.add(new DataFoods("meat", "239", "31.6", "0.0", "10.6", "Meat is a good source of protein, which can help you feel full and boost your metabolism."));
        dataFoods.add(new DataFoods("fish", "208", "19.9", "0.0", "13.6", "Fish is a good source of protein, which can help you feel full and boost your metabolism."));
        
    }
    
//-----------------------------------------------------Main---------------------------------------------------------------
    public static void main(String args[]) {
        fillDataFoods();
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Foods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Foods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Foods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Foods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Foods().setVisible(true);
            }
        });
    }
//------------------------------------------------------------------------------------------------------------------------
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBandAid;
    private javax.swing.JButton jFoods;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jMedicines;
    private javax.swing.JButton jOkSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextSearch;
    private javax.swing.JLabel jadvantage;
    private javax.swing.JLabel jcalories;
    private javax.swing.JLabel jcarb;
    private javax.swing.JLabel jfat;
    private javax.swing.JLabel jfood;
    private javax.swing.JLabel jname;
    private javax.swing.JLabel jprotein;
    // End of variables declaration//GEN-END:variables
}
