import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author PC-Doctor
 */
public class AddFoods extends javax.swing.JFrame {

    /**
     * Creates new form AddFoods
     */

    public AddFoods() {
        initComponents();
    }
    public AddFoods(String adminName) {
        initComponents();
        adminName = adminName.substring(0, 1).toUpperCase() + adminName.substring(1).toLowerCase();
        jAdminName.setText("Welcome, " + adminName);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jAdvantages = new javax.swing.JTextArea();
        jCarbohydrates = new javax.swing.JTextField();
        jCalories = new javax.swing.JTextField();
        jFat = new javax.swing.JTextField();
        jProtein = new javax.swing.JTextField();
        jName = new javax.swing.JTextField();
        jbtnReset = new javax.swing.JButton();
        jbtnAdd = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jfood = new javax.swing.JLabel();
        jAdminName = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbtnLogo = new javax.swing.JButton();
        jbtnPC_Doctor = new javax.swing.JButton();
        jMedicines = new javax.swing.JButton();
        jBandAid = new javax.swing.JButton();
        jFoods = new javax.swing.JButton();
        jbtnSystemLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(170, 80));
        setPreferredSize(new java.awt.Dimension(1460, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(1352, 800));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setForeground(new java.awt.Color(204, 204, 204));
        jPanel6.setName(""); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jAdvantages.setBackground(new java.awt.Color(241, 250, 238));
        jAdvantages.setColumns(20);
        jAdvantages.setFont(new java.awt.Font("FreeSans", 0, 24)); // NOI18N
        jAdvantages.setForeground(new java.awt.Color(0, 0, 0));
        jAdvantages.setLineWrap(true);
        jAdvantages.setRows(5);
        jAdvantages.setWrapStyleWord(true);
        jAdvantages.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Advantages", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Liberation Sans", 1, 24), new java.awt.Color(102, 0, 102))); // NOI18N
        jAdvantages.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jAdvantages);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 1030, 160));

        jCarbohydrates.setBackground(new java.awt.Color(241, 250, 238));
        jCarbohydrates.setFont(new java.awt.Font("FreeSans", 1, 24)); // NOI18N
        jCarbohydrates.setForeground(new java.awt.Color(0, 0, 0));
        jCarbohydrates.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jCarbohydrates.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "carbohydrates", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Liberation Sans", 1, 24), new java.awt.Color(102, 0, 102)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 0, 15), new java.awt.Color(102, 0, 102))); // NOI18N
        jCarbohydrates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCarbohydratesActionPerformed(evt);
            }
        });
        jPanel6.add(jCarbohydrates, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 280, 130));

        jCalories.setBackground(new java.awt.Color(241, 250, 238));
        jCalories.setFont(new java.awt.Font("FreeSans", 1, 24)); // NOI18N
        jCalories.setForeground(new java.awt.Color(0, 0, 0));
        jCalories.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jCalories.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Calories", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Liberation Sans", 1, 24), new java.awt.Color(102, 0, 102)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 0, 15), new java.awt.Color(102, 0, 102))); // NOI18N
        jCalories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCaloriesActionPerformed(evt);
            }
        });
        jPanel6.add(jCalories, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 280, 130));

        jFat.setBackground(new java.awt.Color(241, 250, 238));
        jFat.setFont(new java.awt.Font("FreeSans", 1, 24)); // NOI18N
        jFat.setForeground(new java.awt.Color(0, 0, 0));
        jFat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFat.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fat", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Liberation Sans", 1, 24), new java.awt.Color(102, 0, 102)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 0, 15), new java.awt.Color(102, 0, 102))); // NOI18N
        jFat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFatActionPerformed(evt);
            }
        });
        jPanel6.add(jFat, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 280, 130));

        jProtein.setBackground(new java.awt.Color(241, 250, 238));
        jProtein.setFont(new java.awt.Font("FreeSans", 1, 24)); // NOI18N
        jProtein.setForeground(new java.awt.Color(0, 0, 0));
        jProtein.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jProtein.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Protein", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Liberation Sans", 1, 24), new java.awt.Color(102, 0, 102)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 0, 15), new java.awt.Color(102, 0, 102))); // NOI18N
        jProtein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProteinActionPerformed(evt);
            }
        });
        jPanel6.add(jProtein, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, 280, 130));

        jName.setBackground(new java.awt.Color(241, 250, 238));
        jName.setFont(new java.awt.Font("FreeSans", 1, 24)); // NOI18N
        jName.setForeground(new java.awt.Color(0, 0, 0));
        jName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jName.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Name", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Liberation Sans", 1, 24), new java.awt.Color(102, 0, 102)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Sans", 0, 15), new java.awt.Color(102, 0, 102))); // NOI18N
        jName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNameActionPerformed(evt);
            }
        });
        jPanel6.add(jName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 280, 130));

        jbtnReset.setBackground(new java.awt.Color(204, 204, 204));
        jbtnReset.setFont(new java.awt.Font("URW Gothic", 1, 36)); // NOI18N
        jbtnReset.setForeground(new java.awt.Color(0, 0, 0));
        jbtnReset.setText("Reset");
        jbtnReset.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 570, 150, 100));

        jbtnAdd.setBackground(new java.awt.Color(204, 204, 204));
        jbtnAdd.setFont(new java.awt.Font("URW Gothic", 1, 36)); // NOI18N
        jbtnAdd.setForeground(new java.awt.Color(0, 0, 0));
        jbtnAdd.setText("Add");
        jbtnAdd.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 570, 150, 100));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jfood.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jfood.setForeground(new java.awt.Color(153, 0, 153));
        jfood.setText("Add Foods");
        jPanel1.add(jfood, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        jAdminName.setEditable(false);
        jAdminName.setBackground(new java.awt.Color(153, 153, 153));
        jAdminName.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jAdminName.setForeground(new java.awt.Color(0, 102, 51));
        jAdminName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jAdminName.setText("Welcome");
        jAdminName.setBorder(null);
        jAdminName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAdminNameActionPerformed(evt);
            }
        });
        jPanel1.add(jAdminName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 320, 60));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 113, -1, -1));
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 57, 102, -1));

        jbtnLogo.setBackground(new java.awt.Color(254, 254, 254));
        jbtnLogo.setIcon(new javax.swing.ImageIcon(MainWindow.prefixPath + "/src/main/java/images/Logo.jpg")); // NOI18N
        jbtnLogo.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jbtnLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLogoActionPerformed(evt);
            }
        });
        jPanel5.add(jbtnLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 110, 90));

        jbtnPC_Doctor.setBackground(new java.awt.Color(255, 255, 255));
        jbtnPC_Doctor.setFont(new java.awt.Font("Chilanka", 1, 30)); // NOI18N
        jbtnPC_Doctor.setForeground(new java.awt.Color(0, 0, 0));
        jbtnPC_Doctor.setText("PC Doctor");
        jbtnPC_Doctor.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jbtnPC_Doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPC_DoctorActionPerformed(evt);
            }
        });
        jPanel5.add(jbtnPC_Doctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 170, 50));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 230, 180));

        jMedicines.setBackground(new java.awt.Color(255, 255, 255));
        jMedicines.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMedicines.setForeground(new java.awt.Color(0, 0, 0));
        jMedicines.setIcon(new javax.swing.ImageIcon(MainWindow.prefixPath + "/src/main/java/images/Medicines.png")); // NOI18N
        jMedicines.setText("  Medicines");
        jMedicines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMedicinesActionPerformed(evt);
            }
        });
        jPanel3.add(jMedicines, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 270, 52));

        jBandAid.setBackground(new java.awt.Color(246, 249, 254));
        jBandAid.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jBandAid.setForeground(new java.awt.Color(0, 0, 0));
        jBandAid.setIcon(new javax.swing.ImageIcon(MainWindow.prefixPath + "/src/main/java/images/BandAid.png")); // NOI18N
        jBandAid.setText("   Band Aid ");
        jBandAid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBandAidActionPerformed(evt);
            }
        });
        jPanel3.add(jBandAid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 270, 49));

        jFoods.setBackground(new java.awt.Color(255, 255, 255));
        jFoods.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jFoods.setForeground(new java.awt.Color(0, 0, 0));
        jFoods.setIcon(new javax.swing.ImageIcon(MainWindow.prefixPath + "/src/main/java/images/Food.png")); // NOI18N
        jFoods.setText("    Foods      ");
        jFoods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFoodsActionPerformed(evt);
            }
        });
        jPanel3.add(jFoods, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 270, -1));

        jbtnSystemLogin.setBackground(new java.awt.Color(204, 204, 204));
        jbtnSystemLogin.setFont(new java.awt.Font("FreeMono", 1, 36)); // NOI18N
        jbtnSystemLogin.setForeground(new java.awt.Color(0, 0, 0));
        jbtnSystemLogin.setText("System");
        jbtnSystemLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jbtnSystemLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSystemLoginActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnSystemLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 690, 230, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 316, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(326, 326, 326)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 1140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 750, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLogoActionPerformed
        // TODO add your handling code here:
        MainWindow obj = new MainWindow();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtnLogoActionPerformed

    private void jbtnPC_DoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPC_DoctorActionPerformed
        // TODO add your handling code here:
        jbtnLogo.doClick();
    }//GEN-LAST:event_jbtnPC_DoctorActionPerformed

    private void jMedicinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMedicinesActionPerformed
        // TODO add your handling code here:
        Medicine obj = new Medicine();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMedicinesActionPerformed

    private void jBandAidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBandAidActionPerformed
        // TODO add your handling code here:
        BandAid obj = new BandAid();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBandAidActionPerformed

    private void jFoodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFoodsActionPerformed
        // TODO add your handling code here:
        Foods obj = new Foods();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jFoodsActionPerformed

    private void jbtnSystemLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSystemLoginActionPerformed
        Login obj = new Login();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtnSystemLoginActionPerformed

    private void jCarbohydratesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCarbohydratesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCarbohydratesActionPerformed

    private void jCaloriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCaloriesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCaloriesActionPerformed

    private void jFatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFatActionPerformed

    private void jProteinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProteinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jProteinActionPerformed

    private void jNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNameActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        // TODO add your handling code here:
        jName.setText(null);
        jCalories.setText(null);
        jCarbohydrates.setText(null);
        jFat.setText(null);
        jProtein.setText(null);
        jAdvantages.setText(null);
    }//GEN-LAST:event_jbtnResetActionPerformed
    
    public static String isValid(String val, String name){
        try {
            Double.parseDouble(val);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter a valid number for " + name);
            return "error";
        }
        return null;
    }
    //check if the food already exists in Foods.txt
    public static boolean isExist(String name){
        try {
            File file = new File(MainWindow.prefixPath + "/src/main/java/files/Foods.txt");
            Scanner sc = new Scanner(file);
            while(sc.hasNextLine()){
                String line = sc.nextLine();
                String[] arr = line.split(",");
                if(arr[0].equals(name)){
                    return true;
                }
            }
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        }
        return false;
    }
    public static boolean isValidName(String name){
        int count = 0;
        for(int i = 0; i < name.length(); i++){
            if(Character.isDigit(name.charAt(i))){
                count++;
            }
        }
        if(count == name.length()){
            return false;
        }
        return true;
    }
    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed
        // TODO add your handling code here:
        String name = jName.getText().toLowerCase();
        String calories = jCalories.getText();
        String carbohydrates = jCarbohydrates.getText();
        String fat = jFat.getText();
        String protein = jProtein.getText();
        String advantages = jAdvantages.getText();
        if(!isValidName(name)){
            JOptionPane.showMessageDialog(null, "Please enter a valid name, it can't be only numbers");
            return;
        }
        else if(isExist(name.toLowerCase())){
            JOptionPane.showMessageDialog(null, "This food already exists");
            return;
        }
        else if(name.isEmpty() || calories.isEmpty() || protein.isEmpty() || fat.isEmpty() || carbohydrates.isEmpty() || advantages.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill all the fields");
        }
        else if(isValid(calories, "Calories") == "error" || isValid(protein, "Protein") == "error" || isValid(fat, "Fat") == "error" || isValid(carbohydrates, "Carbohydrates") == "error"){
            return;
        }
        else if(advantages.contains(",")){
            JOptionPane.showMessageDialog(null, "Please do not use ',' in Advantages");
            return;
        }
        else if(!isValidName(advantages)){
            JOptionPane.showMessageDialog(null, "Please enter a valid Advantages, it can't be only numbers");
            return;
        }
        else {
            try {
                // write to file /home/anwar/PC-Doctor/PC-Doctor/src/main/java/files/Foods.txt in append mode
                FileWriter fw = new FileWriter(MainWindow.prefixPath + "/src/main/java/files/Foods.txt", true);
                BufferedWriter bw = new BufferedWriter(fw);
                bw.write(name + "," + calories + "," + protein + "," + carbohydrates + "," + fat + "," + advantages);
                bw.newLine();
                bw.close();
                fw.close();
                JOptionPane.showMessageDialog(null, "Successfully added");
                jbtnReset.doClick();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jbtnAddActionPerformed

    private void jAdminNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAdminNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAdminNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFoods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFoods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFoods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFoods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFoods().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAdminName;
    private javax.swing.JTextArea jAdvantages;
    private javax.swing.JButton jBandAid;
    private javax.swing.JTextField jCalories;
    private javax.swing.JTextField jCarbohydrates;
    private javax.swing.JTextField jFat;
    private javax.swing.JButton jFoods;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jMedicines;
    private javax.swing.JTextField jName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jProtein;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JButton jbtnLogo;
    private javax.swing.JButton jbtnPC_Doctor;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnSystemLogin;
    private javax.swing.JLabel jfood;
    // End of variables declaration//GEN-END:variables
}
