import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;

import javax.swing.JOptionPane;

import com.sun.tools.javac.Main;

/**
 *
 * @author PC-Doctor
 */
public class AddMedicines extends javax.swing.JFrame {

    /**
     * Creates new form AddMedicines
     */
    public AddMedicines() {
        initComponents();
    }
    public AddMedicines(String adminName){
        initComponents();
        adminName = adminName.substring(0, 1).toUpperCase() + adminName.substring(1).toLowerCase();
        jAdminName.setText("Welcome, " + adminName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jDrugDosageLabel = new javax.swing.JLabel();
        jIndicationsLabel = new javax.swing.JLabel();
        jsideEffectsLabel = new javax.swing.JLabel();
        jmedLabel = new javax.swing.JLabel();
        jName = new javax.swing.JTextField();
        jMedRate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jIndications = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jDrugDosage = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jSideEffects = new javax.swing.JTextArea();
        jbtnReset = new javax.swing.JButton();
        jbtnAdd = new javax.swing.JButton();
        jnameLabel1 = new javax.swing.JLabel();
        jnameLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jAdminName = new javax.swing.JTextField();
        jmedicines = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbtnLogo = new javax.swing.JButton();
        jbtnPC_Doctor = new javax.swing.JButton();
        jMedicines = new javax.swing.JButton();
        jBandAid = new javax.swing.JButton();
        jFoods = new javax.swing.JButton();
        jbtnSystemLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(170, 80));
        setResizable(false);
        setSize(new java.awt.Dimension(1352, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDrugDosageLabel.setBackground(new java.awt.Color(204, 204, 204));
        jDrugDosageLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jDrugDosageLabel.setForeground(new java.awt.Color(0, 0, 0));
        jDrugDosageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jDrugDosageLabel.setText("Drug Dosage:");
        jDrugDosageLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        jDrugDosageLabel.setOpaque(true);
        jPanel6.add(jDrugDosageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 60, 250, 45));

        jIndicationsLabel.setBackground(new java.awt.Color(204, 204, 204));
        jIndicationsLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jIndicationsLabel.setForeground(new java.awt.Color(0, 0, 0));
        jIndicationsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jIndicationsLabel.setText("  Indications:");
        jIndicationsLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        jIndicationsLabel.setOpaque(true);
        jPanel6.add(jIndicationsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 210, 45));

        jsideEffectsLabel.setBackground(new java.awt.Color(204, 204, 204));
        jsideEffectsLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jsideEffectsLabel.setForeground(new java.awt.Color(0, 0, 0));
        jsideEffectsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jsideEffectsLabel.setText("  Side Effects:");
        jsideEffectsLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        jsideEffectsLabel.setOpaque(true);
        jPanel6.add(jsideEffectsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 210, 45));

        jmedLabel.setBackground(new java.awt.Color(204, 204, 204));
        jmedLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jmedLabel.setForeground(new java.awt.Color(0, 0, 0));
        jmedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmedLabel.setText("Medication Rating:");
        jmedLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        jmedLabel.setOpaque(true);
        jPanel6.add(jmedLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 300, 45));

        jName.setBackground(new java.awt.Color(241, 250, 238));
        jName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jName.setText("    ");
        jName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNameActionPerformed(evt);
            }
        });
        jPanel6.add(jName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 250, 50));

        jMedRate.setBackground(new java.awt.Color(241, 250, 238));
        jMedRate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMedRate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jMedRate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel6.add(jMedRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 410, 50));

        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jIndications.setBackground(new java.awt.Color(241, 250, 238));
        jIndications.setColumns(20);
        jIndications.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jIndications.setForeground(new java.awt.Color(0, 0, 0));
        jIndications.setLineWrap(true);
        jIndications.setRows(5);
        jIndications.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jIndications);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 320, 330));

        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jDrugDosage.setBackground(new java.awt.Color(241, 250, 238));
        jDrugDosage.setColumns(20);
        jDrugDosage.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jDrugDosage.setForeground(new java.awt.Color(0, 0, 0));
        jDrugDosage.setLineWrap(true);
        jDrugDosage.setRows(5);
        jDrugDosage.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jDrugDosage);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 120, 340, 390));

        jScrollPane3.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jSideEffects.setBackground(new java.awt.Color(241, 250, 238));
        jSideEffects.setColumns(20);
        jSideEffects.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jSideEffects.setForeground(new java.awt.Color(0, 0, 0));
        jSideEffects.setLineWrap(true);
        jSideEffects.setRows(5);
        jSideEffects.setWrapStyleWord(true);
        jScrollPane3.setViewportView(jSideEffects);

        jPanel6.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 320, 330));

        jbtnReset.setBackground(new java.awt.Color(51, 51, 51));
        jbtnReset.setFont(new java.awt.Font("URW Gothic", 1, 36)); // NOI18N
        jbtnReset.setForeground(new java.awt.Color(255, 255, 255));
        jbtnReset.setText("Reset");
        jbtnReset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 620, 310, 80));

        jbtnAdd.setBackground(new java.awt.Color(0, 204, 51));
        jbtnAdd.setFont(new java.awt.Font("URW Gothic", 1, 36)); // NOI18N
        jbtnAdd.setForeground(new java.awt.Color(255, 255, 255));
        jbtnAdd.setText("Add");
        jbtnAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 620, 310, 80));

        jnameLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jnameLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jnameLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jnameLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jnameLabel1.setText("Name: ");
        jnameLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        jnameLabel1.setOpaque(true);
        jPanel6.add(jnameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 140, 45));

        jnameLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jnameLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jnameLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jnameLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jnameLabel2.setText("Name: ");
        jnameLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        jnameLabel2.setOpaque(true);
        jPanel6.add(jnameLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 140, 45));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 1140, 740));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jAdminName.setEditable(false);
        jAdminName.setBackground(new java.awt.Color(153, 153, 153));
        jAdminName.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jAdminName.setForeground(new java.awt.Color(0, 102, 51));
        jAdminName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jAdminName.setText("Welcome");
        jAdminName.setBorder(null);
        jAdminName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAdminNameActionPerformed(evt);
            }
        });
        jPanel1.add(jAdminName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 320, 60));

        jmedicines.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jmedicines.setForeground(new java.awt.Color(189, 52, 72));
        jmedicines.setText("Add Medicines");
        jPanel1.add(jmedicines, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 1140, 60));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 113, -1, -1));
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 57, 102, -1));

        jbtnLogo.setBackground(new java.awt.Color(254, 254, 254));
        jbtnLogo.setIcon(new javax.swing.ImageIcon(MainWindow.prefixPath + "/src/main/java/images/Logo.jpg")); // NOI18N
        jbtnLogo.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jbtnLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLogoActionPerformed(evt);
            }
        });
        jPanel5.add(jbtnLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 110, 90));

        jbtnPC_Doctor.setBackground(new java.awt.Color(255, 255, 255));
        jbtnPC_Doctor.setFont(new java.awt.Font("Chilanka", 1, 30)); // NOI18N
        jbtnPC_Doctor.setForeground(new java.awt.Color(0, 0, 0));
        jbtnPC_Doctor.setText("PC Doctor");
        jbtnPC_Doctor.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jbtnPC_Doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPC_DoctorActionPerformed(evt);
            }
        });
        jPanel5.add(jbtnPC_Doctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 170, 50));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 230, 180));

        jMedicines.setBackground(new java.awt.Color(255, 255, 255));
        jMedicines.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMedicines.setForeground(new java.awt.Color(0, 0, 0));
        jMedicines.setIcon(new javax.swing.ImageIcon(MainWindow.prefixPath + "/src/main/java/images/Medicines.png")); // NOI18N
        jMedicines.setText("  Medicines");
        jMedicines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMedicinesActionPerformed(evt);
            }
        });
        jPanel3.add(jMedicines, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 270, 52));

        jBandAid.setBackground(new java.awt.Color(246, 249, 254));
        jBandAid.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jBandAid.setForeground(new java.awt.Color(0, 0, 0));
        jBandAid.setIcon(new javax.swing.ImageIcon(MainWindow.prefixPath + "/src/main/java/images/BandAid.png")); // NOI18N
        jBandAid.setText("   Band Aid ");
        jBandAid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBandAidActionPerformed(evt);
            }
        });
        jPanel3.add(jBandAid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 270, 49));

        jFoods.setBackground(new java.awt.Color(255, 255, 255));
        jFoods.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jFoods.setForeground(new java.awt.Color(0, 0, 0));
        jFoods.setIcon(new javax.swing.ImageIcon(MainWindow.prefixPath + "/src/main/java/images/Food.png")); // NOI18N
        jFoods.setText("    Foods      ");
        jFoods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFoodsActionPerformed(evt);
            }
        });
        jPanel3.add(jFoods, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 270, -1));

        jbtnSystemLogin.setBackground(new java.awt.Color(204, 204, 204));
        jbtnSystemLogin.setFont(new java.awt.Font("FreeMono", 1, 36)); // NOI18N
        jbtnSystemLogin.setForeground(new java.awt.Color(0, 0, 0));
        jbtnSystemLogin.setText("System");
        jbtnSystemLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jbtnSystemLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSystemLoginActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnSystemLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 690, 230, 70));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 324, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNameActionPerformed

    private void jbtnLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLogoActionPerformed
        // TODO add your handling code here:
        MainWindow obj = new MainWindow();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtnLogoActionPerformed

    private void jbtnPC_DoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPC_DoctorActionPerformed
        // TODO add your handling code here:
        jbtnLogo.doClick();
    }//GEN-LAST:event_jbtnPC_DoctorActionPerformed

    private void jMedicinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMedicinesActionPerformed
        // TODO add your handling code here:
        Medicine obj = new Medicine();
        obj.setVisible(true);
        obj.setVisible(false);
    }//GEN-LAST:event_jMedicinesActionPerformed

    private void jBandAidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBandAidActionPerformed
        // TODO add your handling code here:
        BandAid obj = new BandAid();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBandAidActionPerformed

    private void jFoodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFoodsActionPerformed
        // TODO add your handling code here:
        Foods obj = new Foods();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jFoodsActionPerformed

    private void jbtnSystemLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSystemLoginActionPerformed
        Login obj = new Login();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtnSystemLoginActionPerformed

    private void jAdminNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAdminNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAdminNameActionPerformed


    //check if the Medicine already exists in med.txt
    public static boolean isExist(String name){
        try {
            File file = new File(MainWindow.prefixPath + "/src/main/java/files/med.txt");
            Scanner sc = new Scanner(file);
            while(sc.hasNextLine()){
                String line = sc.nextLine();
                if(line.equals(name)) return true;
                line = sc.nextLine();
                line = sc.nextLine();
                line = sc.nextLine();
                line = sc.nextLine();
            }
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        }
        return false;
    }
    public static boolean isValidName(String name){
        int count = 0;
        for(int i = 0; i < name.length(); i++){
            if(Character.isDigit(name.charAt(i))){
                count++;
            }
        }
        if(count == name.length()){
            return false;
        }
        return true;
    }
    
    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        // TODO add your handling code here:
        jName.setText(null);
        jMedRate.setText(null);
        jDrugDosage.setText(null);
        jSideEffects.setText(null);
        jIndications.setText(null);
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed
        // TODO add your handling code here:
        String name = jName.getText().toLowerCase().trim();
        name = name.substring(0, 1).toUpperCase() + name.substring(1);
        String MedicationRating = jMedRate.getText();
        String DrugDosage = jDrugDosage.getText();
        String SideEffects = jSideEffects.getText();
        String Indications = jIndications.getText();

        if(!isValidName(name)){
            JOptionPane.showMessageDialog(null, "Please enter a valid name, it can't be only numbers");
            return;
        }
        else if(isExist(name)){
            JOptionPane.showMessageDialog(null, "This Medicine already exists");
            return;
        }
        else if(name.isEmpty() || MedicationRating.isEmpty() || DrugDosage.isEmpty() || SideEffects.isEmpty() || Indications.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill all the fields");
            return;
        }
        else {
            try {
                // write to file /home/anwar/PC-Doctor/PC-Doctor/src/main/java/files/Foods.txt in append mode
                FileWriter fw = new FileWriter(MainWindow.prefixPath + "/src/main/java/files/med.txt", true);
                BufferedWriter bw = new BufferedWriter(fw);
                bw.write(name);
                bw.newLine();
                bw.write(MedicationRating);
                bw.newLine();
                bw.write(DrugDosage);
                bw.newLine();
                bw.write(SideEffects);
                bw.newLine();
                bw.write(Indications);
                bw.newLine();
                bw.close();
                fw.close();
                JOptionPane.showMessageDialog(null, "Successfully added");
                jbtnReset.doClick();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jbtnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMedicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMedicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMedicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMedicines.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMedicines().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAdminName;
    private javax.swing.JButton jBandAid;
    private javax.swing.JTextArea jDrugDosage;
    private javax.swing.JLabel jDrugDosageLabel;
    private javax.swing.JButton jFoods;
    private javax.swing.JTextArea jIndications;
    private javax.swing.JLabel jIndicationsLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jMedRate;
    private javax.swing.JButton jMedicines;
    private javax.swing.JTextField jName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jSideEffects;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JButton jbtnLogo;
    private javax.swing.JButton jbtnPC_Doctor;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnSystemLogin;
    private javax.swing.JLabel jmedLabel;
    private javax.swing.JLabel jmedicines;
    private javax.swing.JLabel jnameLabel1;
    private javax.swing.JLabel jnameLabel2;
    private javax.swing.JLabel jsideEffectsLabel;
    // End of variables declaration//GEN-END:variables
}
