
import javax.swing.JFrame;
import java.io.File;
import java.io.IOException;
import java.util.Scanner;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author PC-Doctor
 */

public class BandAid extends javax.swing.JFrame {

    /**
     * Creates new form BandAid
     */
    public BandAid() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDiabeticBleeding = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jbtnEpilepticFit = new javax.swing.JButton();
        jbtnSevereBleeding = new javax.swing.JButton();
        jbtnShortnessOfBreath = new javax.swing.JButton();
        jbtnFainting = new javax.swing.JButton();
        jbtnBurns = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtYouShouldNotDo = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtxtYouShouldDo = new javax.swing.JTextArea();
        jPanel13 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jbtnLogo = new javax.swing.JButton();
        jbtnPC_Doctor = new javax.swing.JButton();
        jMedicines = new javax.swing.JButton();
        jBandAid = new javax.swing.JButton();
        jFoods = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jfood = new javax.swing.JLabel();

        jDiabeticBleeding.setBackground(new java.awt.Color(204, 255, 255));
        jDiabeticBleeding.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jDiabeticBleeding.setForeground(new java.awt.Color(0, 0, 0));
        jDiabeticBleeding.setText("Diabetic Bleeding");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 255, 255));
        jButton1.setText("Epileptic Fit");

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 255, 255));
        jButton2.setText("Fainting");

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 255, 255));
        jButton3.setText("Burns");

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(204, 255, 255));
        jButton4.setText("Shortness Of Breath");

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText(" Choose The Emergency");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText(" You Should Do: ");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText(" You Shouldn't Do: ");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(170, 80));
        setPreferredSize(new java.awt.Dimension(1460, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(1352, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1574, 822, 150, -1));

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 822, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 822, -1, -1));

        jPanel5.setBackground(new java.awt.Color(51, 0, 51));
        jPanel5.setForeground(new java.awt.Color(51, 0, 51));
        jPanel5.setLayout(new java.awt.CardLayout());
        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1418, 828, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnEpilepticFit.setBackground(new java.awt.Color(153, 153, 153));
        jbtnEpilepticFit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnEpilepticFit.setForeground(new java.awt.Color(0, 0, 0));
        jbtnEpilepticFit.setText("Epileptic Fit");
        jbtnEpilepticFit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEpilepticFitActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnEpilepticFit, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 390, 300, 40));

        jbtnSevereBleeding.setBackground(new java.awt.Color(153, 153, 153));
        jbtnSevereBleeding.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnSevereBleeding.setForeground(new java.awt.Color(0, 0, 0));
        jbtnSevereBleeding.setText("Severe Bleeding");
        jbtnSevereBleeding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSevereBleedingActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnSevereBleeding, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 210, 300, 40));

        jbtnShortnessOfBreath.setBackground(new java.awt.Color(153, 153, 153));
        jbtnShortnessOfBreath.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnShortnessOfBreath.setForeground(new java.awt.Color(0, 0, 0));
        jbtnShortnessOfBreath.setText("Shortness Of Breath");
        jbtnShortnessOfBreath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnShortnessOfBreathActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnShortnessOfBreath, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 300, -1, 41));

        jbtnFainting.setBackground(new java.awt.Color(153, 153, 153));
        jbtnFainting.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnFainting.setForeground(new java.awt.Color(0, 0, 0));
        jbtnFainting.setText("Fainting");
        jbtnFainting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFaintingActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnFainting, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 480, 300, 40));

        jbtnBurns.setBackground(new java.awt.Color(153, 153, 153));
        jbtnBurns.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnBurns.setForeground(new java.awt.Color(0, 0, 0));
        jbtnBurns.setText("Burns");
        jbtnBurns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBurnsActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnBurns, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 570, 300, 40));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 7));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText(" Choose The Emergency ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 22, -1, -1));

        jPanel9.setBackground(new java.awt.Color(153, 153, 153));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 7));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("You Should Do:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jPanel4.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 111, -1, -1));

        jtxtYouShouldNotDo.setEditable(false);
        jtxtYouShouldNotDo.setColumns(20);
        jtxtYouShouldNotDo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtYouShouldNotDo.setRows(5);
        jScrollPane1.setViewportView(jtxtYouShouldNotDo);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 464, 760, 243));

        jtxtYouShouldDo.setEditable(false);
        jtxtYouShouldDo.setColumns(20);
        jtxtYouShouldDo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtYouShouldDo.setRows(5);
        jScrollPane3.setViewportView(jtxtYouShouldDo);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 172, 760, 201));

        jPanel13.setBackground(new java.awt.Color(153, 153, 153));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 7));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("You Shouldn't Do:");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        jPanel4.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 391, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 1140, 740));

        jPanel6.setBackground(new java.awt.Color(57, 62, 70));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 113, -1, -1));
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 57, 102, -1));

        jbtnLogo.setBackground(new java.awt.Color(254, 254, 254));
        jbtnLogo.setIcon(new javax.swing.ImageIcon(MainWindow.prefixPath + "/src/main/java/images/Logo.jpg")); // NOI18N
        jbtnLogo.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jbtnLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLogoActionPerformed(evt);
            }
        });
        jPanel8.add(jbtnLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 110, 90));

        jbtnPC_Doctor.setBackground(new java.awt.Color(255, 255, 255));
        jbtnPC_Doctor.setFont(new java.awt.Font("Chilanka", 1, 30)); // NOI18N
        jbtnPC_Doctor.setForeground(new java.awt.Color(0, 0, 0));
        jbtnPC_Doctor.setText("PC Doctor");
        jbtnPC_Doctor.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jbtnPC_Doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPC_DoctorActionPerformed(evt);
            }
        });
        jPanel8.add(jbtnPC_Doctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 170, 50));

        jPanel6.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 230, 180));

        jMedicines.setBackground(new java.awt.Color(255, 255, 255));
        jMedicines.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMedicines.setForeground(new java.awt.Color(0, 0, 0));
        jMedicines.setIcon(new javax.swing.ImageIcon(MainWindow.prefixPath + "/src/main/java/images/Medicines.png")); // NOI18N
        jMedicines.setText("  Medicines");
        jMedicines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMedicinesActionPerformed(evt);
            }
        });
        jPanel6.add(jMedicines, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 270, 52));

        jBandAid.setBackground(new java.awt.Color(246, 249, 254));
        jBandAid.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jBandAid.setForeground(new java.awt.Color(0, 0, 0));
        jBandAid.setIcon(new javax.swing.ImageIcon(MainWindow.prefixPath + "/src/main/java/images/BandAid.png")); // NOI18N
        jBandAid.setText("   Band Aid ");
        jBandAid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBandAidActionPerformed(evt);
            }
        });
        jPanel6.add(jBandAid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 270, 49));

        jFoods.setBackground(new java.awt.Color(255, 255, 255));
        jFoods.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jFoods.setForeground(new java.awt.Color(0, 0, 0));
        jFoods.setIcon(new javax.swing.ImageIcon(MainWindow.prefixPath + "/src/main/java/images/Food.png")); // NOI18N
        jFoods.setText("    Foods      ");
        jFoods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFoodsActionPerformed(evt);
            }
        });
        jPanel6.add(jFoods, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 270, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 324, 800));

        jPanel10.setBackground(new java.awt.Color(57, 62, 70));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jfood.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jfood.setForeground(new java.awt.Color(255, 255, 255));
        jfood.setText("Band Aid");
        jPanel10.add(jfood, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 1150, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnShortnessOfBreathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnShortnessOfBreathActionPerformed
        File doFile = new File(MainWindow.prefixPath + "/src/main/java/files/breathdo.txt");
        File notFile = new File(MainWindow.prefixPath + "/src/main/java/files/breathnot.txt");
        Scanner sc;
        
        //you should 
        try {
            sc = new Scanner(doFile);
            String data;
            jtxtYouShouldDo.setText("");
            while (sc.hasNextLine()) {
                data = sc.nextLine();
                jtxtYouShouldDo.setText(jtxtYouShouldDo.getText() + data + "\n");
            }
        }
        catch (Exception e) {
            System.out.println("Error when read breath do file");
        }
        
        //you shouldn't do
        try {
            sc = new Scanner(notFile);
            String data;
            jtxtYouShouldNotDo.setText("");
            while (sc.hasNextLine()) {
                data = sc.nextLine();
                jtxtYouShouldNotDo.setText(jtxtYouShouldNotDo.getText() + data + "\n");
            }
        }
        catch (Exception e) {
            System.out.println("Error when read breath not file");
        }
        
    }//GEN-LAST:event_jbtnShortnessOfBreathActionPerformed

    private void jbtnEpilepticFitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEpilepticFitActionPerformed
        // TODO add your handling code here:
        File doFile = new File(MainWindow.prefixPath + "/src/main/java/files/epilepticdo.txt");
        File notFile = new File(MainWindow.prefixPath + "/src/main/java/files/epilepticnot.txt");
        Scanner sc;
        
        //you should 
        try {
            sc = new Scanner(doFile);
            String data;
            jtxtYouShouldDo.setText("");
            while (sc.hasNextLine()) {
                data = sc.nextLine();
                jtxtYouShouldDo.setText(jtxtYouShouldDo.getText() + data + "\n");
            }
        }
        catch (Exception e) {
            System.out.println("Error when read Epileptic do file");
        }
        
        //you shouldn't do
        try {
            sc = new Scanner(notFile);
            String data;
            jtxtYouShouldNotDo.setText("");
            while (sc.hasNextLine()) {
                data = sc.nextLine();
                jtxtYouShouldNotDo.setText(jtxtYouShouldNotDo.getText() + data + "\n");
            }
        }
        catch (Exception e) {
            System.out.println("Error when read Epileptic not file");
        }
        
    }//GEN-LAST:event_jbtnEpilepticFitActionPerformed

    private void jbtnFaintingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFaintingActionPerformed
        File doFile = new File(MainWindow.prefixPath + "/src/main/java/files/faintingdo.txt");
        File notFile = new File(MainWindow.prefixPath + "/src/main/java/files/faintingnot.txt");
        Scanner sc;
        
        //you should 
        try {
            sc = new Scanner(doFile);
            String data;
            jtxtYouShouldDo.setText("");
            while (sc.hasNextLine()) {
                data = sc.nextLine();
                jtxtYouShouldDo.setText(jtxtYouShouldDo.getText() + data + "\n");
            }
        }
        catch (Exception e) {
            System.out.println("Error when read Fainting do file");
        }
        
        //you shouldn't do
        try {
            sc = new Scanner(notFile);
            String data;
            jtxtYouShouldNotDo.setText("");
            while (sc.hasNextLine()) {
                data = sc.nextLine();
                jtxtYouShouldNotDo.setText(jtxtYouShouldNotDo.getText() + data + "\n");
            }
        }
        catch (Exception e) {
            System.out.println("Error when read Fainting not file");
        }
        
        
    }//GEN-LAST:event_jbtnFaintingActionPerformed

    private void jbtnSevereBleedingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSevereBleedingActionPerformed
        //you should
        File doFile = new File(MainWindow.prefixPath + "/src/main/java/files/bleedingdo.txt");
        File notFile = new File(MainWindow.prefixPath + "/src/main/java/files/bleedingnot.txt");
        Scanner sc;
        
        //you should 
        try {
            sc = new Scanner(doFile);
            String data;
            jtxtYouShouldDo.setText("");
            while (sc.hasNextLine()) {
                data = sc.nextLine();
                jtxtYouShouldDo.setText(jtxtYouShouldDo.getText() + data + "\n");
            }
        }
        catch (Exception e) {
            System.out.println("Error when read Bleeding do file");
        }
        
        //you shouldn't do
        try {
            sc = new Scanner(notFile);
            String data;
            jtxtYouShouldNotDo.setText("");
            while (sc.hasNextLine()) {
                data = sc.nextLine();
                jtxtYouShouldNotDo.setText(jtxtYouShouldNotDo.getText() + data + "\n");
            }
        }
        catch (Exception e) {
            System.out.println("Error when read Bleeding not file");
        }
        
    }//GEN-LAST:event_jbtnSevereBleedingActionPerformed

    private void jbtnBurnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBurnsActionPerformed
        // TODO add your handling code here:
        File doFile = new File(MainWindow.prefixPath + "/src/main/java/files/burnsdo.txt");
        File notFile = new File(MainWindow.prefixPath + "/src/main/java/files/burnsnot.txt");
        Scanner sc;
        
        //you should 
        try {
            sc = new Scanner(doFile);
            String data;
            jtxtYouShouldDo.setText("");
            while (sc.hasNextLine()) {
                data = sc.nextLine();
                jtxtYouShouldDo.setText(jtxtYouShouldDo.getText() + data + "\n");
            }
        }
        catch (Exception e) {
            System.out.println("Error when read Burns do file");
        }
        
        //you shouldn't do
        try {
            sc = new Scanner(notFile);
            String data;
            jtxtYouShouldNotDo.setText("");
            while (sc.hasNextLine()) {
                data = sc.nextLine();
                jtxtYouShouldNotDo.setText(jtxtYouShouldNotDo.getText() + data + "\n");
            }
        }
        catch (Exception e) {
            System.out.println("Error when read Burns not file");
        }
        
    }//GEN-LAST:event_jbtnBurnsActionPerformed

    private void jbtnLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLogoActionPerformed
        // TODO add your handling code here:
        MainWindow obj = new MainWindow();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtnLogoActionPerformed

    private void jbtnPC_DoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPC_DoctorActionPerformed
        // TODO add your handling code here:
        jbtnLogo.doClick();
    }//GEN-LAST:event_jbtnPC_DoctorActionPerformed

    private void jMedicinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMedicinesActionPerformed
        // TODO add your handling code here:
        Medicine obj = new Medicine();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMedicinesActionPerformed

    private void jBandAidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBandAidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBandAidActionPerformed

    private void jFoodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFoodsActionPerformed
        // TODO add your handling code here:
        Foods obj = new Foods();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jFoodsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BandAid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BandAid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BandAid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BandAid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BandAid frame = new BandAid();
//                frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
//                frame.setResizable(false);
//                frame.pack();
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBandAid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jDiabeticBleeding;
    private javax.swing.JButton jFoods;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton jMedicines;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton jbtnBurns;
    private javax.swing.JButton jbtnEpilepticFit;
    private javax.swing.JButton jbtnFainting;
    private javax.swing.JButton jbtnLogo;
    private javax.swing.JButton jbtnPC_Doctor;
    private javax.swing.JButton jbtnSevereBleeding;
    private javax.swing.JButton jbtnShortnessOfBreath;
    private javax.swing.JLabel jfood;
    private javax.swing.JTextArea jtxtYouShouldDo;
    private javax.swing.JTextArea jtxtYouShouldNotDo;
    // End of variables declaration//GEN-END:variables
}
