import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

import javax.swing.JOptionPane;

/**
 *
 * @author anwar
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        jbtnAddFoods.setEnabled(false);
        jbtnAddMedicines.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLoginPanel = new javax.swing.JPanel();
        jUserName = new javax.swing.JTextField();
        jUserPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jbtnSystemLogin1 = new javax.swing.JButton();
        jbtnLogin = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnAddMedicines = new javax.swing.JButton();
        jbtnAddFoods = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbtnLogo = new javax.swing.JButton();
        jbtnPC_Doctor = new javax.swing.JButton();
        jMedicines = new javax.swing.JButton();
        jBandAid = new javax.swing.JButton();
        jFoods = new javax.swing.JButton();
        jbtnSystemLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(170, 80));
        setResizable(false);
        setSize(new java.awt.Dimension(1352, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setName(""); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rammetto One", 1, 90)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 1, 1));
        jLabel1.setText("System Login");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, 120));

        jLabel6.setIcon(new javax.swing.ImageIcon(MainWindow.prefixPath + "/src/main/java/images/system.png")); // NOI18N
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 210, 260, 260));
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

        jLoginPanel.setBackground(new java.awt.Color(255, 255, 255));
        jLoginPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jLoginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jUserName.setBackground(new java.awt.Color(255, 255, 255));
        jUserName.setFont(new java.awt.Font("FreeSans", 0, 36)); // NOI18N
        jUserName.setForeground(new java.awt.Color(51, 51, 51));
        jUserName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUserNameActionPerformed(evt);
            }
        });
        jLoginPanel.add(jUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 300, 70));

        jUserPassword.setBackground(new java.awt.Color(255, 255, 255));
        jUserPassword.setFont(new java.awt.Font("FreeSans", 0, 36)); // NOI18N
        jUserPassword.setForeground(new java.awt.Color(51, 51, 51));
        jUserPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jUserPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUserPasswordActionPerformed(evt);
            }
        });
        jLoginPanel.add(jUserPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 300, 70));

        jLabel5.setFont(new java.awt.Font("Lato Semibold", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Password:");
        jLoginPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 210, 70));

        jLabel7.setFont(new java.awt.Font("Lato Semibold", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("UserName:");
        jLoginPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 210, 70));

        jbtnSystemLogin1.setBackground(new java.awt.Color(0, 0, 0));
        jbtnSystemLogin1.setFont(new java.awt.Font("FreeMono", 1, 36)); // NOI18N
        jbtnSystemLogin1.setForeground(new java.awt.Color(204, 255, 255));
        jbtnSystemLogin1.setText("System");
        jbtnSystemLogin1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jbtnSystemLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSystemLogin1ActionPerformed(evt);
            }
        });
        jLoginPanel.add(jbtnSystemLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 690, 230, 70));

        jbtnLogin.setBackground(new java.awt.Color(255, 255, 255));
        jbtnLogin.setFont(new java.awt.Font("Dyuthi", 1, 36)); // NOI18N
        jbtnLogin.setForeground(new java.awt.Color(0, 0, 0));
        jbtnLogin.setText("Login");
        jbtnLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });
        jLoginPanel.add(jbtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 180, 70));

        jbtnReset.setBackground(new java.awt.Color(255, 255, 255));
        jbtnReset.setFont(new java.awt.Font("Dyuthi", 1, 36)); // NOI18N
        jbtnReset.setForeground(new java.awt.Color(0, 0, 0));
        jbtnReset.setText("Reset");
        jbtnReset.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jLoginPanel.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 180, 70));

        jPanel6.add(jLoginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 630, 320));

        jbtnAddMedicines.setBackground(new java.awt.Color(255, 255, 255));
        jbtnAddMedicines.setFont(new java.awt.Font("Dyuthi", 1, 36)); // NOI18N
        jbtnAddMedicines.setForeground(new java.awt.Color(0, 0, 0));
        jbtnAddMedicines.setText("Add Medicines");
        jbtnAddMedicines.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jbtnAddMedicines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddMedicinesActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnAddMedicines, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 250, 90));

        jbtnAddFoods.setBackground(new java.awt.Color(255, 255, 255));
        jbtnAddFoods.setFont(new java.awt.Font("Dyuthi", 1, 36)); // NOI18N
        jbtnAddFoods.setForeground(new java.awt.Color(0, 0, 0));
        jbtnAddFoods.setText("Add Foods");
        jbtnAddFoods.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jbtnAddFoods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddFoodsActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnAddFoods, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 250, 90));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 1140, 800));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 113, -1, -1));
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 57, 102, -1));

        jbtnLogo.setBackground(new java.awt.Color(254, 254, 254));
        jbtnLogo.setIcon(new javax.swing.ImageIcon(MainWindow.prefixPath + "/src/main/java/images/Logo.jpg")); // NOI18N
        jbtnLogo.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jbtnLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLogoActionPerformed(evt);
            }
        });
        jPanel5.add(jbtnLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 110, 90));

        jbtnPC_Doctor.setBackground(new java.awt.Color(255, 255, 255));
        jbtnPC_Doctor.setFont(new java.awt.Font("Chilanka", 1, 30)); // NOI18N
        jbtnPC_Doctor.setForeground(new java.awt.Color(0, 0, 0));
        jbtnPC_Doctor.setText("PC Doctor");
        jbtnPC_Doctor.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jbtnPC_Doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPC_DoctorActionPerformed(evt);
            }
        });
        jPanel5.add(jbtnPC_Doctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 170, 50));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 230, 180));

        jMedicines.setBackground(new java.awt.Color(255, 255, 255));
        jMedicines.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMedicines.setForeground(new java.awt.Color(0, 0, 0));
        jMedicines.setIcon(new javax.swing.ImageIcon(MainWindow.prefixPath + "/src/main/java/images/Medicines.png")); // NOI18N
        jMedicines.setText("  Medicines");
        jMedicines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMedicinesActionPerformed(evt);
            }
        });
        jPanel3.add(jMedicines, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 270, 52));

        jBandAid.setBackground(new java.awt.Color(246, 249, 254));
        jBandAid.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jBandAid.setForeground(new java.awt.Color(0, 0, 0));
        jBandAid.setIcon(new javax.swing.ImageIcon(MainWindow.prefixPath + "/src/main/java/images/BandAid.png")); // NOI18N
        jBandAid.setText("   Band Aid ");
        jBandAid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBandAidActionPerformed(evt);
            }
        });
        jPanel3.add(jBandAid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 270, 49));

        jFoods.setBackground(new java.awt.Color(255, 255, 255));
        jFoods.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jFoods.setForeground(new java.awt.Color(0, 0, 0));
        jFoods.setIcon(new javax.swing.ImageIcon(MainWindow.prefixPath + "/src/main/java/images/Food.png")); // NOI18N
        jFoods.setText("    Foods      ");
        jFoods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFoodsActionPerformed(evt);
            }
        });
        jPanel3.add(jFoods, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 270, -1));

        jbtnSystemLogin.setBackground(new java.awt.Color(204, 204, 204));
        jbtnSystemLogin.setFont(new java.awt.Font("FreeMono", 1, 36)); // NOI18N
        jbtnSystemLogin.setForeground(new java.awt.Color(0, 0, 0));
        jbtnSystemLogin.setText("System");
        jbtnSystemLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jbtnSystemLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSystemLoginActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnSystemLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 690, 230, 70));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 324, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLogoActionPerformed
        MainWindow obj = new MainWindow();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtnLogoActionPerformed

    private void jbtnPC_DoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPC_DoctorActionPerformed
        jbtnLogo.doClick();
    }//GEN-LAST:event_jbtnPC_DoctorActionPerformed

    private void jMedicinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMedicinesActionPerformed
        // TODO add your handling code here:
        Medicine obj = new Medicine();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMedicinesActionPerformed

    private void jBandAidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBandAidActionPerformed
        // TODO add your handling code here:
        BandAid obj = new BandAid();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBandAidActionPerformed

    private void jFoodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFoodsActionPerformed
        // TODO add your handling code here:
        Foods obj = new Foods();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jFoodsActionPerformed

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed
        //check if the user name and password is correct from users.txt
        String userName = jUserName.getText();
        //get the password from the jPasswordField
        String userPassword = new String(jUserPassword.getPassword());
        String user = userName + "," + userPassword;
        String line = null;
        boolean found = false;
        try {
            File file = new File(MainWindow.prefixPath + "/src/main/java/files/users.txt");
            Scanner sc = new Scanner(file);
            while (sc.hasNextLine()) {
                line = sc.nextLine();
                System.out.println(line + " " + user);
                if (line.equals(user)) {
                    found = true;
                    jbtnAddFoods.setEnabled(true);
                    jbtnAddMedicines.setEnabled(true);
                    jUserName.setEnabled(false);
                    jUserPassword.setEnabled(false);
                    jbtnLogin.setEnabled(false);
                    jbtnReset.setEnabled(false);
                    jLoginPanel.setBackground(new java.awt.Color(222, 225, 229));
                    jLabel6.setIcon(new javax.swing.ImageIcon(MainWindow.prefixPath + "/src/main/java/images/colored-system.png"));
                    break;
                }
            }
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        }
        if (!found) {
            JOptionPane.showMessageDialog(null, "User name or password is incorrect");
        }
        
    }//GEN-LAST:event_jbtnLoginActionPerformed

    private void jUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUserNameActionPerformed

    private void jUserPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUserPasswordActionPerformed
        // TODO add your handling code here:
        jbtnLogin.doClick();
    }//GEN-LAST:event_jUserPasswordActionPerformed

    private void jbtnSystemLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSystemLogin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnSystemLogin1ActionPerformed

    private void jbtnAddMedicinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddMedicinesActionPerformed
  
    }//GEN-LAST:event_jbtnAddMedicinesActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReset1ActionPerformed
        jUserName.setText(null);
        jUserPassword.setText(null);
    }//GEN-LAST:event_jbtnReset1ActionPerformed

    private void jbtnAddFoodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddFoodsActionPerformed
        // TODO add your handling code here:
        AddFoods obj = new AddFoods(jUserName.getText());
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtnAddFoodsActionPerformed

    private void jbtnSystemLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSystemLoginActionPerformed
        Login obj = new Login();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtnSystemLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBandAid;
    private javax.swing.JButton jFoods;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jLoginPanel;
    private javax.swing.JButton jMedicines;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jUserName;
    private javax.swing.JPasswordField jUserPassword;
    private javax.swing.JButton jbtnAddFoods;
    private javax.swing.JButton jbtnAddMedicines;
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JButton jbtnLogo;
    private javax.swing.JButton jbtnPC_Doctor;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnSystemLogin;
    private javax.swing.JButton jbtnSystemLogin1;
    // End of variables declaration//GEN-END:variables
}
